apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/infrastructure/aws-load-balancer-controller
  - ../../../base/infrastructure/external-secrets
  - ../../../base/infrastructure/karpenter
  - ../../../base/infrastructure/storage
