apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/infrastructure/prometheus
  - ../../../base/infrastructure/loki
  - ../../../base/infrastructure/promtail
patches:
  - path: patches/prometheus-values.yaml
