apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  role: ${cluster_name}-karpenter-node

  amiSelectorTerms:
    - alias: al2023@latest

  subnetSelectorTerms:
    - tags:
        kubernetes.io/cluster/${cluster_name}: "shared"
        kubernetes.io/role/internal-elb: "1"

  securityGroupSelectorTerms:
    - tags:
        aws:eks:cluster-name: ${cluster_name}

  kubelet:
    maxPods: 110

  tags:
    ManagedBy: karpenter
